---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake test"
matrix:
  include:
    - rvm: 2.2.4
      env: PUPPET_VERSION="~> 4.4"
    - rvm: 2.4.4
      env: PUPPET_VERSION="~> 5.0"
    - rvm: 2.5.3
      env: PUPPET_VERSION="~> 6.0"

notifications:
  email: false
